name: build-and-test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 35
    env:
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 6

    steps:
      - uses: actions/checkout@v1

      - name: Setup - Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.1"

      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install Dependencies
        run: |
          gem install xcpretty

      - name: Lint
        run: |
          swiftlint --version
          bundle exec fastlane lint

      - name: Test
        run: bundle exec fastlane tests
